sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.0
before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.travis config/secrets.yml
  - bundle exec rake db:create db:migrate